# Generated by Django 4.2.6 on 2023-12-12 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Macaroni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_of_purchase', models.CharField(max_length=20)),
                ('card_number', models.CharField(max_length=20, null=True)),
                ('product_code', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=255)),
                ('product_group', models.CharField(max_length=50)),
                ('cash_register_number', models.IntegerField()),
                ('quantity', models.FloatField()),
                ('price_list_amount', models.FloatField()),
                ('total_amount_due', models.FloatField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.file')),
            ],
        ),
    ]
