# Generated by Django 4.2.6 on 2023-12-12 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_file_title'),
        ('files', '0003_macaroni'),
    ]

    operations = [
    ]
