# Generated by Django 4.2.6 on 2023-12-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_supply_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='balance_first',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='supply',
            name='balance_storage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='supply',
            name='price_storage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='supply',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='supply',
            name='profit_clean',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='supply',
            name='profit_missed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='supply',
            name='sell',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='supply',
            name='supply',
            field=models.FloatField(default=0.0),
        ),
    ]
