# Generated by Django 4.2.6 on 2023-12-13 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date', models.DateField()),
                ('supply', models.FloatField()),
                ('balance_first', models.FloatField()),
                ('sell', models.FloatField()),
                ('balance_storage', models.FloatField()),
                ('price_storage', models.FloatField()),
                ('profit', models.FloatField()),
                ('profit_clean', models.FloatField()),
                ('profit_missed', models.FloatField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
    ]
