# Generated by Django 4.2.6 on 2023-12-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_supply_balance_first_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='price_storage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='supply',
            name='profit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='supply',
            name='profit_clean',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='supply',
            name='profit_missed',
            field=models.FloatField(default=0.0),
        ),
    ]
